### ISSUE TITLE
upgrade Linux 5.15.74-1-pve with patch T2 driver (PROXMOX)

### ISSUE THREAD

**Issue by barzag** [andersfugmann/T2-Debian-Kernel#7]
Hello,

I am looking for the possibility of updating my Kernel proxmox (Linux 5.15.74-1-pve) with the patches and the T2 drivers. I use a macmini 8.1. Thanks

**Comment by andersfugmann** [comment]
Is proxmox a linux distribution? The kernel provided here are for the stock debian distribution,
If you want to add you own patch-set to the linux kernel build you will need to compile your own kernel.

Have you tried the latest kernel supplied here? I dont know what extra patched the proxmox distribution applied to the vanilla kernel, but it seems that stock debian does support lxc, and the kernels supplied here do support KVM.

**Comment by barzag** [comment]
Actually proxmox uses the debian distribution. here is the last version "pve kernel" 
[https://github.com/fabianishere/pve-edge-kernel/releases](https://github.com/fabianishere/pve-edge-kernel/releases)

can you provide me with the drivers or patches for the macmini8.1 so that i can try to compile the kernel?

**Comment by andersfugmann** [comment]
You can derive the needed patches from the workflow.
Look at the lines [github/workflows/build.yml#L143](https://github.com/andersfugmann/T2-Debian-Kernel/blob/6ce48b921651df03fdf7423b00850d4bcf62fd31/.github/workflows/build.yml#L143) down to [github/workflows/build.yml#L160](https://github.com/andersfugmann/T2-Debian-Kernel/blob/6ce48b921651df03fdf7423b00850d4bcf62fd31/.github/workflows/build.yml#L160) for instruction on how to fetch and apply patches. 

The SHA's can be found in [build_params](https://github.com/andersfugmann/T2-Debian-Kernel/releases/download/v6.0.10-1/build_params) from the releases. 

Also remember to set the correct configuration parameters. See [.github/workflows/build.yml#L173](https://github.com/andersfugmann/T2-Debian-Kernel/blob/6ce48b921651df03fdf7423b00850d4bcf62fd31/.github/workflows/build.yml#L173) to  [.github/workflows/build.yml#L177](https://github.com/andersfugmann/T2-Debian-Kernel/blob/6ce48b921651df03fdf7423b00850d4bcf62fd31/.github/workflows/build.yml#L177) .

Alternatively, you could fork this repo and change the way the kernel sources are fetched ([.github/workflows/build.yml#L141](https://github.com/andersfugmann/T2-Debian-Kernel/blob/6ce48b921651df03fdf7423b00850d4bcf62fd31/.github/workflows/build.yml#L141)). If you do, you prob want to skip the step that copies in the kernel config from the official debian kernel.

**Comment by andersfugmann** [comment]
Keep in mind that these patches are made for apple T2 macbooks. I dont know if macmini's uses the same architecture.

**Comment by barzag** [comment]
Unfortunately, that's beyond my abilities. Thanks anyway
