### ISSUE TITLE
Error: out of memory from GRUB

### ISSUE THREAD

**Issue by AshleighTheCutie** [andersfugmann/T2-Debian-Kernel#9]
As the title says. I can supply more info as needed, but it's been a problem since at least 6.6.1

EDIT: Also, my WiFi card is unreliable, the keyboard backlight doesn't work, and the machine when in "sleep" mode has the battery die within 7 hours

**Comment by andersfugmann** [comment]
Sorry for the late reply. 

OOM from GRUB is strange. Have you tried `rEFInd` bootloader?

There are a lot of known problems with the kernel, including wifi, suspend etc. I suggest going to the [discord](https://discord.com/invite/68MRhQu) server and ask for help there. There might also be help to be find on the [t2linux](https://wiki.t2linux.org/) site.

**Comment by trazfr** [comment]
Hello,

Maybe this OOM error is linked to the size of the kernels packages and modules.
I have noticed that the deb images produced for some time are huge. [v6.7.2-1](https://github.com/andersfugmann/T2-Debian-Kernel/releases/tag/v6.7.2-1) is ~1GB whereas the older ones were <80MB, see [v6.5.9-3](https://github.com/andersfugmann/T2-Debian-Kernel/releases/tag/v6.5.9-3) for instance. [Ubuntu v6.7.2-1](https://github.com/t2linux/T2-Ubuntu-Kernel/releases/tag/v6.7.2-1) is ~130MB.

The initrd on my laptop are also huge. My last working kernel is `6.6.4`:
```bash
$ ls -lh /boot/initrd.img-6.*
-rw-r--r-- 1 root root  62M Dec 21 21:12 /boot/initrd.img-6.6.4-t2
-rw-r--r-- 1 root root 494M Jan 26 17:31 /boot/initrd.img-6.7.2-t2
```

I guess this is because the `debug_info` are present (taking a big module as an example):

```bash
$ ls -l /lib/modules/**/mlx5_core.ko*
-rw-r--r-- 1 root root 4.2M Dec  3 19:14 /lib/modules/6.6.4-t2/kernel/drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.ko
-rw-r--r-- 1 root root  16M Jan 26 01:42 /lib/modules/6.7.2-t2/kernel/drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.ko.xz

$ xzcat /lib/modules/6.7.2-t2/kernel/drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.ko.xz | wc -c
98197360
# ~93MB

$ file /lib/modules/6.6.4-t2/kernel/drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.ko
/lib/modules/6.6.4-t2/kernel/drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.ko: ELF 64-bit LSB relocatable, x86-64, version 1 (SYSV), BuildID[sha1]=c64f5b8c88f6dfa11dc2b90f77495e9a567f6b49, not stripped

$ xzcat /lib/modules/6.7.2-t2/kernel/drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.ko.xz | file -
/dev/stdin: ELF 64-bit LSB relocatable, x86-64, version 1 (SYSV), BuildID[sha1]=68227783fb222731b3aa1bf31991c3d679beef01, with debug_info, not stripped
```

**Comment by trazfr** [comment]
Comparing [Ubuntu](https://github.com/t2linux/T2-Ubuntu-Kernel/releases/download/v6.7.2-1/kernel_config_6.7.2-mantic) and [debian](https://github.com/andersfugmann/T2-Debian-Kernel/releases/download/v6.7.2-1/kernel_config_6.7.2):

```bash
$ diff -u kernel_config_6.7.2-mantic kernel_config_6.7.2 | grep '^.CONFIG_DEBUG_INFO'
+CONFIG_DEBUG_INFO=y
-CONFIG_DEBUG_INFO_NONE=y
# ...
```

**Comment by andersfugmann** [comment]
I see. I've updated the config to match ubuntu's wrt. `CONFIG_DEBUG_XXX` options.
Thanks for helping in identifying the problem. I'll close the issue once the build is complete and shows a smaller deb package.

**Comment by andersfugmann** [comment]
Success: linux-image-6.7.2-t2_6.7.2-1_amd64.deb is now only 74 MB
 (about half the size of the ubuntu images for some reason). 
Thanks again for the help on resolving this issue.

**Comment by trazfr** [comment]
:wave: Hello,

Thanks a lot! The new kernel 6.7.2-t2 is successfully booting (I'm running it right now).

```bash
$ uname -a
Linux macbook 6.7.2-t2 #1 SMP PREEMPT_DYNAMIC Tue Jan 30 11:11:43 UTC 2024 x86_64 GNU/Linux
```
